spring.application.name=auth-service
server.port=4005

jwt.secret=fyfgPnukEBCqnVS0FC6qNrQs+6FVaKIFF9IY6woS0V5r7O7dXhOkmDoO6Lg1I3f6hVAH29q4xLb+DTsLzzesXg==
# spring.datasource.url=jdbc:postgresql://localhost:5432/db
# spring.datasource.username=postgres
# spring.datasource.password=password
# spring.jpa.hibernate.ddl-auto=update
# spring.sql.init.mode=always