server.port=4000
spring.application.name=patient-service
spring.kafka.bootstrap-servers=13.62.89.182:9092
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.ByteArraySerializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.ByteArrayDeserializer
spring.datasource.url=jdbc:postgresql://13.62.89.182:5432/patient_db
spring.datasource.username=postgres
spring.datasource.password=password